baseURL = "http://example.org/"
title = "Docs Demo"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
sectionPagesMenu = "main"
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""
# Code highlighting options
# Hugo uses Chroma but names are the same as the old pygments highlighter

# Highlight shortcode and code fences (```) will be treated similarly
pygmentscodefences = true

# Change highlight style here.
# For a full list see: https://xyproto.github.io/splash/docs/all.html
pygmentsStyle = "tango" # "emacs" # "autumn" # "manni" # "friendly"

# Other Chroma options can be added here (and in the highlight shortcode in the markdown file)
# See list of supported options: https://gohugo.io/content-management/syntax-highlighting/#options
# for example: pygmentsoptions = "linenos=true"
[params]
	# General information
	author = "John Deng"
	description = "Documentations demo site."
	copyright = "Released under the Apache 2.0 license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/john-deng/hugo-material-docs"

	version = "1.0.0"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "indigo"
    	accent  = "deep-purple"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	github  = "john-deng"
	email   = "hello@email.com"
[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
[outputs]
	home = [ "HTML", "JSON"]
	page = [ "HTML", "JSON"]

